name: Vault Radar Scan (via Container)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  vault-radar:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🛡️ Run Vault Radar inside container
        env:
          HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
          HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
          HCP_PROJECT_ID: ${{ secrets.HCP_PROJECT_ID }}
        run: |
          set +e
          docker run --rm \
            --platform linux/amd64 \
            --env HCP_CLIENT_ID \
            --env HCP_CLIENT_SECRET \
            --env HCP_PROJECT_ID \
            -v "$PWD":/data \
            -w /data \
            repping/vault-radar-cli \
            scan folder \
            --path . \
            --disable-ui \
            --outfile scan_file \
            --format csv
          EXIT_CODE=$?

          if [[ -f scan_file ]]; then
            echo "✅ scan_file generated"
            echo ""
            echo "🔍 Vault Radar Findings:"
            echo "------------------------"
            cat scan_file
            echo "------------------------"
          else
            echo "❌ scan_file NOT generated"
            ls -lh
          fi

          mkdir -p findings
          mv scan_file findings/ || true

          exit $EXIT_CODE

      - name: 📦 Archive scan results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: radar-scan-results
          path: findings/scan_file
