name: Vault Radar Scan (via Container)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  vault-radar:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🛡️ Run Vault Radar inside container
        env:
          HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
          HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
          HCP_PROJECT_ID: ${{ secrets.HCP_PROJECT_ID }}
        run: |
          docker run --rm \
            --platform linux/amd64 \
            --env HCP_CLIENT_ID \
            --env HCP_CLIENT_SECRET \
            --env HCP_PROJECT_ID \
            -v "$PWD":/data \
            -w /data \
            repping/vault_radar_container \
            scan folder \
            --path . \
            --disable-ui \
            --outfile scan_file \
            --format csv || true

      - name: 📦 Archive scan results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: radar-scan-results
          path: scan_file
